# cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[advisories]
# Deny all security vulnerabilities
vulnerability = "deny"
# Warn on unmaintained crates
unmaintained = "warn"
# Warn on unsound crates
unsound = "warn"
# Warn on yanked crates
yanked = "warn"
# Ignore specific advisories (add if needed)
ignore = []

[licenses]
# Allow only these licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "Unlicense",
]
confidence-threshold = 0.8

[bans]
# Deny multiple versions of the same crate
multiple-versions = "warn"
# Warn about wildcards in dependencies
wildcards = "warn"
# Allow these specific crates to have multiple versions
skip = []
# Deny specific crates
deny = []

[sources]
# Deny sources that aren't from crates.io or GitHub
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
